name = "usapalletsolution"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[env.production]
routes = [
  { pattern = "usapalletsolution.org", zone_name = "usapalletsolution.org" }
]
